name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set-up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install npm package
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Run Build
      run: npm run build

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --destination-path '$web' --pattern './dist/*' --source . --account-name ${{secrets.AZURE_STORAGE_ACCOUNT}} --account-key ${{secrets.AZURE_STORAGE_KEY}} --auth-mode key --overwrite

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "cloud-resume-challenge-cdn" --name "lesediresume" --resource-group "cloud-resume-challenge"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
